<?php
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();
$con = mysqli_connect('localhost', 'root', '', 'seminar');

curl_setopt($ch, CURLOPT_URL, 'https://graph.facebook.com/v17.0/348752975333902?fields=posts%7Bmessage%2Ccreated_time%2Cfull_picture%2Cpermalink_url%7D%2Cname%2Cpicture%2Calbums%7Bphotos%7Bpage_story_id%2Cpicture%7D%7D&access_token=EAAwpB2ZAGixoBALZAZBaZB0Lz8FziH6EUXZCdTdEZApKUIBcJOj5wKHCNSH05uUsqod0QtfwBHudw7ZBjuZAzvNeAVNWEkJEPEUeTAv44fLnInljVb2ejDgOjC3QZC7ZBs7gyGDd7SsvKXgWAa6KUYridKAdBZBZBDj5Gjdvg7UOFCy7FcVb70ZBMjRGOzvWLeWzaGlTIDcyIWMDhx7RDy7SVSlon');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);
$result = json_decode($result);
//$con1 = "DELETE FROM baiviet";
mysqli_query ($con, "delete from baiviet");
mysqli_query ($con, "delete from posts_items");
mysqli_query ($con, "delete from fanpages");

// tạo data bài posts
foreach ($result->posts->data as $list) {
    //  $con1= "DELETE FROM baiviet";
    $full_picture = '';
    $message = '';
    if (isset($list->full_picture)) {
        $full_picture = $list->full_picture;
    }
    if (isset($list->message)) {
        $message = $list->message;
    }
    $created_time = $list->created_time;
    $post_id = $list->id;
    $name = $result->name;
    $picture = $result->picture;
    $permalink_url =$list->permalink_url;
   // $con1 = "DELETE FROM baiviet";

   mysqli_query($con, "insert into baiviet(name,full_picture,message,created_time,post_id,permalink_url) values ('$name','$full_picture','$message','$created_time','$post_id','$permalink_url')");


}   
// lưu nhiều hình ảnh trên cùng 1 bài posts
foreach ($result->albums->data as $data) {
    foreach ($data->photos->data as $data1) {
        // $con2= "DELETE FROM posts_items";
        $picture = $data1->picture;
        $page_story_id = $data1->page_story_id;
        $name = $result->name;
       
        mysqli_query($con, "insert into posts_items(name,picture,page_story_id) values ('$name','$picture','$page_story_id')");
    }
}
// data fanpages
foreach ($result->picture as $picture) {
    $name = $result->name;
    $HinhAnh =  $picture->url;
    $link = $result->link;
    mysqli_query($con, "insert into fanpages(HinhAnh,name,link) values ('$HinhAnh','$name','$link')");
}